PROG1   = detectx_client
OBJS1   = main.c ACAP.c cJSON.c Model.c Hub.c Video.c Output.c Output_crop_cache.c Output_helpers.c Output_http.c imgprovider.c imgutils.c MQTT.c CERTS.c labelparse.c
PROGS   = $(PROG1)
LIBDIR  = lib
INCDIR  = include

PKGS = gio-2.0 gio-unix-2.0 vdostream fcgi axevent libcurl

CFLAGS += -I./$(INCDIR)
LDFLAGS += -L./$(LIBDIR) -Wl,-rpath,'$$ORIGIN/lib'
LDLIBS  += -ljpeg -lturbojpeg -s -lm -ldl -lpthread

CFLAGS += $(shell PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) pkg-config --cflags $(PKGS))
LDLIBS += $(shell PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) pkg-config --libs $(PKGS))

CFLAGS += -Wall -Wno-format-overflow -Wno-format-truncation

all: $(PROGS)

$(PROG1): $(OBJS1)
	$(CC) $(CFLAGS) $(LDFLAGS) $^ $(LDLIBS) -o $@

clean:
	rm -rf $(PROGS) *.o *.eap* *_LICENSE.txt package.conf* param.conf tmp* $(LIBDIR) manifest.json
